---
title: "R Notebook"
output: html_notebook
---

```{r Package Installation}
pacman::p_load (dplyr,tidyverse, readr,tidyr, igraph, graphlayouts, ggraph, devtools, tm, tidygraph, devtools)
install_github('cbail/textnets')
```

```{r Data Install}
data = readRDS('cocktail.rds')
```
##Which cocktails are made by only one bartender?
```{r}
dist_bartenders <- unique(as.character(data$bartender))
dist_bartenders <- as.data.frame(dist_bartenders)
count(dist_bartenders)
data$bartender
```

```{r}
lev_bartender<- levels(data$bartender)
lev_bartender
data$lev_bartender <- levels(data$bartender)

duplicated(data2$cocktail_name)
data2$bartender[!duplicated(data2$bartender)]

data2 <- data
head(data)
```
```{r}
Vec_bartender <- as.vector(data$bartender)
Vec_cocktail <- as.vector(data$cocktail_name)
            
```

```{r}
```



```{r}
#looking at the summaries, the number of cocktails have decreased since they all have a frequency of 1, no duplicates. 
summary(data2)
```


```{r}
#removing all the duplicate bartender names.  

bar_data <- data2 %>%
  group_by(bartender) %>%
  select(cocktail_name, bartender) %>%
  na.omit() %>%
  subset(!duplicated(bartender)) %>%
  summary()
  
bar_data
  

```
```{r}
#removing all the duplicate cocktail drink names. 
cock_data <- data2 %>%
  group_by(cocktail_name) %>%
  select(cocktail_name, bartender) %>%
  na.omit() %>%
  subset(!duplicated(cocktail_name)) %>%
  summary()

cock_data

```

```{r}

```

```{r}
graph2 <- cock_data %>%
  as_tbl_graph()

graph2
```

```{r}



graph2 %>%
  ggraph(layout = "stress") +
  geom_edge_fan(aes(start_cap = circle(2, "mm"),
                    end_cap = circle(2, "mm"))) +
  geom_node_point(color = "black") +
  theme_graph() +
  #geom_node_text(aes(label = name))
NULL
  
```

```{r}
data_edges_nodes <- data[c(2,1)]
head(data_edges_nodes)

graph_tg <- data_edges_nodes %>%
  na.omit() %>%
  as_tbl_graph()

graph_tg

graph_tg %>%
  ggraph(layout = "stress") +
  geom_edge_fan(aes(start_cap = circle(2, "mm"),
                    end_cap = circle(2, "mm"))) +
  geom_node_point(color = "black") +
  theme_graph() +
  #geom_node_text(aes(label = name))
NULL
  


```

```{r}

```

```{r}
graph <- graph_from_data_frame(data_edges, directed = F, vertices = data_nodes)
is.igraph(graph)

plot(graph)
```

Which cocktails are made by only one bartender? (degree centrality/betweenness centrality) 
```{r}

```

##Which ingredients are the most popular to use? (degree centrality/betweenness centrality) Darren

```{r}
install_github('cbail/textnets')
library(textnets)
```

```{r}
data_ing <- data %>%
  select(ingredients)
head(data_ing)
# data_ing <- data_ing[1:50,]

data_ing %>%
  mutate_if(is.factor, as.character) -> data_ing
```
```{r}
corpus <- Corpus(VectorSource(data_ing))
tdm <- DocumentTermMatrix(corpus)

# Plotting the incidence graph data
plot(doc_graph_inc, edge.color = "gray30", edge.width = E(doc_graph_inc)$weight)
```


```{r}
ingredients %>%
  filter(cocktail_name == "martinez")
```
```{r}
ingredients %>%
  filter(cocktail_name == "neighborhood negroni")
```



```{r}
tbl_graph <- as_tbl_graph(ingredients)
tbl_graph
plot(tbl_graph)
```


```{r}
prepped_data <- PrepText(ingredients, groupvar = "cocktail_name", textvar = "ingredients", node_type = "groups", tokenizer = "words", pos = "nouns", remove_stop_words = TRUE, compound_nouns = TRUE)
```

```{r}
text_network <- CreateTextnet(prepped_data)
```

```{r}
VisTextNet(text_network, label_degree_cut = 0, betweenness = TRUE)
```

```{r}
VisTextNetD3(text_network, zoom = TRUE)
```



